2022-10-06 18:21:37,779 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NywiZXhwIjoxNjY1MDU1ODc3Ljk2MDc2ODJ9.WpzMveR3F5nbdRcRThWQVHv9FConLg3FdUeixG9XXFk [GET] [in /home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/auth/routes.py", line 106, in reset_password
    return render_template('auth/reset_password.html', form=form)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/auth/reset_password.html", line 34, in top-level template code
    {{ wtf.quick_form(form, size=50) }}
TypeError: macro 'quick_form' takes no keyword argument 'size'
2022-10-06 18:22:01,638 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 18:28:58,162 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 18:52:02,045 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 18:53:52,294 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NywiZXhwIjoxNjY1MDU3NzU2LjU3Mzk1fQ.1obVwU81lQDuXN6Gh-ZFZxxllKA_R6vyqMTDXryg3QE [GET] [in /home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/auth/routes.py", line 106, in reset_password
    return render_template('auth/reset_password.html', form=form)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/auth/reset_password.html", line 43, in top-level template code
    {% for error in form.email.errors %}
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.auth.forms.ResetPasswordForm object' has no attribute 'email'
2022-10-06 18:54:22,293 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 19:01:56,258 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 19:04:04,496 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 19:16:29,208 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 19:35:23,114 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
