2022-10-06 02:51:05,985 ERROR: Exception on /homepage [GET] [in /home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/main/routes.py", line 24, in homepage
    return render_template('home.html')
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %} asdasd {% endblock %}
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/base.html", line 54, in template
    {{ 'username', username=current_user.username }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2022-10-06 02:51:28,284 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 02:51:31,409 ERROR: Exception on /homepage [GET] [in /home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/main/routes.py", line 24, in homepage
    return render_template('home.html')
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %} asdasd {% endblock %}
  File "/home/duonglieumoc/OneDrive/python_program/website/venvy/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/base.html", line 54, in template
    {{ ('username', username=current_user.username) }}
jinja2.exceptions.TemplateSyntaxError: expected token ')', got '='
2022-10-06 02:51:55,691 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 02:52:47,518 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 02:54:26,463 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 02:55:56,321 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 02:56:39,353 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 02:57:38,353 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 02:59:56,556 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:00:59,833 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:02:29,066 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:03:31,088 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:03:45,505 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:04:22,819 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:04:41,997 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:06:39,982 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:06:56,973 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:08:33,289 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:09:42,352 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:10:36,556 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:14:14,708 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-06 03:14:39,509 INFO: ANACOM logs [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
